name: Finish update

on:
  workflow_call:
    inputs:
      old_branch:
        required: true
        type: string
      new_branch:
        required: false
        type: string
      old_version:
        required: true
        type: string
      new_version:
        required: true
        type: string
      fix_getlevel:
        required: false
        type: boolean


env:
  JAVA_VERSION: 17

jobs:
  common:
    runs-on: ubuntu-latest
    outputs:
      jdk_version: ${{ steps.java_version.outputs.result }}
      version_type: ${{ fromJson(steps.split_version.outputs.result).new_version_type }}
      version_name: ${{ fromJson(steps.split_version.outputs.result).new_version_name }}
      old_version_type: ${{ fromJson(steps.split_version.outputs.result).old_version_type }}
      old_version_name: ${{ fromJson(steps.split_version.outputs.result).old_version_name }}
      branch: ${{ inputs.new_branch || fromJson(steps.split_version.outputs.result).old_branch }}
      old_branch: ${{ fromJson(steps.split_version.outputs.result).old_branch }}
    steps:
    - name: Get Time
      id: time
      run: echo "::set-output name=time::$(date -Isecond -u)"
    - uses: actions/github-script@v6
      id: split_version
      env:
        OLD_VERSION: ${{ inputs.old_version }}
        NEW_VERSION: ${{ inputs.new_version }}
        OLD_BRANCH: ${{ inputs.old_branch }}
      with:
        script: |
          const oldVersion = process.env.OLD_VERSION.split("/");
          const newVersion = process.env.NEW_VERSION.split("/");
          var returnValue = {new_version_name: newVersion[newVersion.length - 1], old_version_name: oldVersion[oldVersion.length - 1], new_version_type: newVersion[0], old_version_type: oldVersion[0], old_branch: process.env.OLD_BRANCH.replace(/^[^/]+\//, '')}
          return returnValue;
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/cache@v3
      name: Cache ${{ fromJson(steps.split_version.outputs.result).new_version_name }}
      with:
        path: |
          build/versions/${{ fromJson(steps.split_version.outputs.result).new_version_name }}/**
          versions/${{ inputs.new_version }}/build/download-task/**
        key: version-v3-${{ fromJson(steps.split_version.outputs.result).new_version_name }}
    - uses: actions/cache@v3
      name: Cache Assets
      with:
        path: build/assets/**
        key: minecraft-assets-v3-${{ steps.time.outputs.time }}
        restore-keys: |
          minecraft-assets-v3-
    - uses: actions/cache@v3
      name: Cache Libraries
      with:
        path: build/libraries/**
        key: minecraft-libraries-v3-${{ steps.time.outputs.time }}
        restore-keys: |
          minecraft-libraries-v3-
    - uses: actions/cache@v3
      name: Cache Version Manifest
      with:
        path: build/versions/version_manifest.json
        key: minecraft-version-manifest-v3-${{ steps.time.outputs.time }}
        restore-keys: |
          minecraft-version-manifest-v3-
    - uses: actions/cache@v3
      name: Cache BuildSrc
      with:
        path: |
          buildSrc/build/**
          buildSrc/.gradle/**
        key: buildsrc-build-jdk${{ env.JAVA_VERSION }}-v3-${{ steps.time.outputs.time }}
        restore-keys: |
          buildsrc-build-jdk${{ env.JAVA_VERSION }}-v3-
    - uses: actions/cache@v3
      name: Cache Other
      with:
        path: |
          build/download-task/**
          .gradle/**
        key: gradle-other-${{ steps.time.outputs.time }}
        restore-keys: |
          gradle-other-  
    - run: |
        git remote add upstream https://github.com/MinecraftForge/MCPConfig
        git fetch upstream
        git checkout -B ${{ fromJson(steps.split_version.outputs.result).old_branch }} remotes/${{ inputs.old_branch }}
    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v3
      with:
        java-version: '${{ env.JAVA_VERSION }}'
        distribution: 'temurin'
    - if: ${{ inputs.new_branch }}
      run: |
        git checkout ${{ inputs.new_branch }}
    - run: |
        git config --global user.name github-actions
        git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
    - name: Apply and Create patches
      id: patches
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      continue-on-error: true
      with:
        arguments: :${{ fromJson(steps.split_version.outputs.result).new_version_name }}:projectApplyAll :${{ fromJson(steps.split_version.outputs.result).new_version_name }}:projectMakeAll -Ptype=${{ fromJson(steps.split_version.outputs.result).new_version_type }}
    - if: ${{ steps.patches.outcome == 'success' }}
      name: Check if patches have changed
      id: check_changes
      continue-on-error: true
      run: |
        git add .
        git diff-index --quiet HEAD
    - if: ${{ steps.check_changes.outcome == 'failure' }}
      run: |
        git commit -m "Update patches"
        git push
    - name: Make Zip
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: :${{ fromJson(steps.split_version.outputs.result).new_version_name }}:makeZip -Ptype=${{ fromJson(steps.split_version.outputs.result).new_version_type }}
    - name: Upload Zip as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: mcp_config-${{ fromJson(steps.split_version.outputs.result).new_version_name }}
        path: build/distributions/*.zip
    - name: Get Java Version
      id: java_version
      uses: actions/github-script@v6
      env:
        VERSION: ${{ inputs.new_version }}
        PATCHES_OUTCOME: ${{ steps.patches.outcome }}
      with:
        result-encoding: "string"
        script: |
          if (process.env.PATCHES_OUTCOME != 'success') {
            return Number.MAX_SAFE_INTEGER;
          }
          const fs = require('fs');
          const config = JSON.parse(fs.readFileSync('versions/' + process.env.VERSION + '/config.json', 'utf8'))
          return config.java_target;
  
  get-diff:
    name: Get diff
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: common
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
    - uses: actions/cache@v3
      name: Cache ${{ needs.common.outputs.version_name }}
      with:
        path: |
          build/versions/${{ needs.common.outputs.version_name }}/**
          versions/${{ inputs.new_version }}/build/download-task/**
        key: version-v3-${{ needs.common.outputs.version_name }}
    - uses: actions/cache@v3
      name: Cache ${{ needs.common.outputs.old_version_name }}
      with:
        path: |
          build/versions/${{ needs.common.outputs.old_version_name }}/**
          versions/${{ inputs.old_version }}/build/download-task/**
        key: version-v3-${{ needs.common.outputs.old_version_name }}
    - uses: actions/cache@v3
      name: Cache Assets
      with:
        path: build/assets/**
        key: minecraft-assets-v3-${{ steps.time.outputs.time }}
        restore-keys: |
          minecraft-assets-v3-
    - uses: actions/cache@v3
      name: Cache Libraries
      with:
        path: build/libraries/**
        key: minecraft-libraries-v3-${{ steps.time.outputs.time }}
        restore-keys: |
          minecraft-libraries-v3-
    - uses: actions/cache@v3
      name: Cache Version Manifest
      with:
        path: build/versions/version_manifest.json
        key: minecraft-version-manifest-v3-${{ steps.time.outputs.time }}
        restore-keys: |
          minecraft-version-manifest-v3-
    - uses: actions/cache@v3
      name: Cache BuildSrc
      with:
        path: |
          buildSrc/build/**
          buildSrc/.gradle/**
        key: buildsrc-build-jdk17-v3-${{ steps.time.outputs.time }}
        restore-keys: |
          buildsrc-build-jdk17-v3-
    - uses: actions/cache@v3
      name: Cache Other
      with:
        path: |
          build/download-task/**
          .gradle/**
        key: gradle-other-${{ steps.time.outputs.time }}
        restore-keys: |
          gradle-other-  
    - run: |
        git remote add upstream https://github.com/MinecraftForge/MCPConfig
        git fetch upstream
        git checkout -B ${{ needs.common.outputs.old_branch }} remotes/${{ inputs.old_branch }}
    - name: Get old joined src
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: :${{ needs.common.outputs.old_version_name }}:projectApplyAll -Pupdating -Ptype=${{ needs.common.outputs.old_version_type }}
    - name: Checkout new branch
      if: ${{ inputs.new_branch }}
      run: git checkout ${{ inputs.new_branch }}
    - name: Get new joined src
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: :${{ needs.common.outputs.version_name }}:projectApplyAll -Pupdating -Ptype=${{ needs.common.outputs.version_type }}
    - name: Get diff
      continue-on-error: true
      run: git diff --no-index versions/${{ inputs.old_version }}/projects/joined/src/main/java versions/${{ inputs.new_version }}/projects/joined/src/main/java > ${{ needs.common.outputs.old_version_name }}-${{ needs.common.outputs.version_name }}.patch
    - name: Upload diff as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ needs.common.outputs.old_version_name }}-${{ needs.common.outputs.version_name }}-patch
        path: '*.patch'

  testjdks:
    name: Test Jdks on side ${{ matrix.side }} using mappings ${{ matrix.mappings }} using java version ${{ matrix.jdk_version }} 
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: common
    strategy:
      fail-fast: false
      matrix:
        jdk_version: [8, 11, 16, 17, 18]
        mappings: [Official, HotSpot]
        side: [Client, Joined, Server]
        exclude:
        - jdk_version: 11
          mappings: HotSpot
    
    steps: 
    - uses: actions/checkout@v3
      with:
        ref: ${{ needs.common.outputs.branch }}
    - name: Set up JDK ${{ matrix.jdk_version }}
      if: ${{ matrix.jdk_version != env.JAVA_VERSION}}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.jdk_version }}
        distribution: 'temurin'
    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
    - name: Get Time
      id: time
      run: echo "::set-output name=time::$(date -Isecond -u)"
    - uses: actions/cache@v3
      name: Cache ${{ needs.common.outputs.version_name }}
      with:
        path: |
          build/versions/${{ needs.common.outputs.version_name }}/**
          versions/${{ inputs.new_version }}/build/download-task/**
        key: version-v3-${{ needs.common.outputs.version_name }}
    - uses: actions/cache@v3
      name: Cache Assets
      with:
        path: build/assets/**
        key: minecraft-assets-v3-${{ steps.time.outputs.time }}
        restore-keys: |
          minecraft-assets-v3-
    - uses: actions/cache@v3
      name: Cache Libraries
      with:
        path: build/libraries/**
        key: minecraft-libraries-v3-${{ steps.time.outputs.time }}
        restore-keys: |
          minecraft-libraries-v3-
    - uses: actions/cache@v3
      name: Cache Version Manifest
      with:
        path: build/versions/version_manifest.json
        key: minecraft-version-manifest-v3-${{ steps.time.outputs.time }}
        restore-keys: |
          minecraft-version-manifest-v3-
    - uses: actions/cache@v3
      name: Cache BuildSrc
      with:
        path: |
          buildSrc/build/**
          buildSrc/.gradle/**
        key: buildsrc-build-jdk${{ matrix.jdk_version }}-v3-${{ steps.time.outputs.time }}
        restore-keys: |
          buildsrc-build-jdk${{ matrix.jdk_version }}-v3-
    - uses: actions/cache@v3
      name: Cache Other
      with:
        path: |
          build/download-task/**
          .gradle/**
        key: gradle-other-${{ steps.time.outputs.time }}
        restore-keys: |
          gradle-other-  
    - name: Test jdks
      if: ${{ matrix.jdk_version >= needs.common.outputs.jdk_version}}
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: :${{ needs.common.outputs.version_name }}:testCompile${{ matrix.side }}${{ matrix.mappings }}${{ matrix.jdk_version }} :${{ needs.common.outputs.version_name }}:testDecompile${{ matrix.side }}${{ matrix.mappings }}${{ matrix.jdk_version }}Compare -Ptype=${{ needs.common.outputs.version_type }}

      
